import {
    Wifi,
    Wind,
    Tv,
    Armchair,
    Plug,
    Zap,
    BedDouble,
    UtensilsCrossed,
    Music2,
    Thermometer,
    Coffee,
    MonitorPlay,
} from "lucide-react";

// Amenity icon map — add as many as needed; unknown ones get a text badge
export const AMENITY_ICONS = {
    Wifi: <Wifi className="w-4 h-4" />,
    AC: <Wind className="w-4 h-4" />,
    "Air Conditioning": <Wind className="w-4 h-4" />,
    TV: <Tv className="w-4 h-4" />,
    Leather: <Armchair className="w-4 h-4" />,
    Seats: <Armchair className="w-4 h-4" />,
    Restroom: <MonitorPlay className="w-4 h-4" />,
    WC: <MonitorPlay className="w-4 h-4" />,
    Power: <Plug className="w-4 h-4" />,
    "USB Charging": <Plug className="w-4 h-4" />,
    USB: <Plug className="w-4 h-4" />,
    Outlet: <Zap className="w-4 h-4" />,
    Beds: <BedDouble className="w-4 h-4" />,
    Bed: <BedDouble className="w-4 h-4" />,
    Kitchen: <UtensilsCrossed className="w-4 h-4" />,
    Food: <UtensilsCrossed className="w-4 h-4" />,
    Music: <Music2 className="w-4 h-4" />,
    Entertainment: <Music2 className="w-4 h-4" />,
    Heating: <Thermometer className="w-4 h-4" />,
    Coffee: <Coffee className="w-4 h-4" />,
    Refreshments: <Coffee className="w-4 h-4" />,
};
