export const FILTERS = [
    { id: "all", label: "All Vehicles" },
    { id: "small", label: "Small (8-20)" },
    { id: "medium", label: "Medium (20-40)" },
    { id: "large", label: "Large (40+)" },
];

export const COUNTRY_CODES = [
    { code: "+1", name: "USA / Canada" },
    { code: "+7", name: "Russia" },
    { code: "+20", name: "Egypt" },
    { code: "+27", name: "South Africa" },
    { code: "+30", name: "Greece" },
    { code: "+31", name: "Netherlands" },
    { code: "+32", name: "Belgium" },
    { code: "+33", name: "France" },
    { code: "+34", name: "Spain" },
    { code: "+36", name: "Hungary" },
    { code: "+39", name: "Italy" },
    { code: "+40", name: "Romania" },
    { code: "+41", name: "Switzerland" },
    { code: "+43", name: "Austria" },
    { code: "+44", name: "United Kingdom" },
    { code: "+45", name: "Denmark" },
    { code: "+46", name: "Sweden" },
    { code: "+47", name: "Norway" },
    { code: "+48", name: "Poland" },
    { code: "+49", name: "Germany" },
    { code: "+52", name: "Mexico" },
    { code: "+55", name: "Brazil" },
    { code: "+60", name: "Malaysia" },
    { code: "+61", name: "Australia" },
    { code: "+62", name: "Indonesia" },
    { code: "+63", name: "Philippines" },
    { code: "+64", name: "New Zealand" },
    { code: "+65", name: "Singapore" },
    { code: "+66", name: "Thailand" },
    { code: "+81", name: "Japan" },
    { code: "+82", name: "South Korea" },
    { code: "+84", name: "Vietnam" },
    { code: "+86", name: "China" },
    { code: "+90", name: "Turkey" },
    { code: "+91", name: "India" },
    { code: "+92", name: "Pakistan" },
    { code: "+93", name: "Afghanistan" },
    { code: "+94", name: "Sri Lanka" },
    { code: "+95", name: "Myanmar" },
    { code: "+98", name: "Iran" },
    { code: "+212", name: "Morocco" },
    { code: "+213", name: "Algeria" },
    { code: "+216", name: "Tunisia" },
    { code: "+234", name: "Nigeria" },
    { code: "+254", name: "Kenya" },
    { code: "+255", name: "Tanzania" },
    { code: "+351", name: "Portugal" },
    { code: "+352", name: "Luxembourg" },
    { code: "+353", name: "Ireland" },
    { code: "+358", name: "Finland" },
    { code: "+380", name: "Ukraine" },
    { code: "+420", name: "Czech Republic" },
    { code: "+421", name: "Slovakia" },
    { code: "+971", name: "UAE" },
    { code: "+972", name: "Israel" },
    { code: "+973", name: "Bahrain" },
    { code: "+974", name: "Qatar" },
    { code: "+975", name: "Bhutan" },
    { code: "+976", name: "Mongolia" },
    { code: "+977", name: "Nepal" },
    { code: "+998", name: "Uzbekistan" },
];
